#!/system/bin/sh

# Galaxy Tab 2 7.0 auto rotation script
# Ketut P. Kumajaya, Sept 2013

# make sure the touchcreen driver in landscape mode
echo 0 > /sys/devices/virtual/sec/tsp/pivot
# set accelerometer position, landscape mode
position=$(find /sys/devices/virtual/input/ -type f -name name | xargs grep '^accelerometer$' | sed 's@name:accelerometer@position@')
echo -n 7 > $position
# set geomagnetic position, landscape mode
position=$(find /sys/devices/platform/omap/omap_i2c.4/i2c-4/4-002e/input/ -type f -name name | xargs grep '^geomagnetic$' | sed 's@name:geomagnetic@position@')
echo -n 7 > $position
